website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Note, PostForm
from . import db
import json
from .models import UserForm, User, Cars
views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')

    return render_template("home.html", user=current_user)

@views.route('/admin')
@login_required
def admin():
    id = current_user.id
    if id == 1:
        return render_template("admin.html", user=current_user)
    else:
        flash("Sorry you must be an Admin to Access this page")
        return redirect(url_for('dashboard'))

    
@views.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    form = UserForm()
    id= current_user.id
    name_to_update = User.query.get_or_404(id)
    if request.method == "POST":
        name_to_update.full_name = request.form['full_name']
        name_to_update.email = request.form['email']
        name_to_update.age = request.form['age']
        name_to_update.user_name = request.form['user_name']
        try:
            db.session.commit()
            flash("User Updated Successfully!!")
            return render_template("dashboard.html", form=form, name_to_update=name_to_update)
        except:
            flash("Error! Looks like there was a problem updating ur profile")
            return render_template("dashboard.html", form=form, name_to_update=name_to_update)
    else:
        return render_template("dashboard.html", form=form, name_to_update=name_to_update, id= id)
    return render_template("dashboard.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

@views.route('/rental', methods=[ 'POST', 'GET'])
def rental():
        
    #Grab all the posts from the form
    rental = Cars.query.order_by(Cars.date_posted)
    return render_template("rental.html", rental= rental)

@views.route('/history', methods=[ 'POST', 'GET'])
def history():
    rented = Cars.query.order_by(Cars.date_posted)
    if request.method == 'POST':
        rented = request.form.get('note')
    
    return render_template('history.html', rented=rented)

@views.route('/create_car', methods=[ 'POST', 'GET'])
def create_car():
    form = PostForm()
    if form.validate_on_submit():
        car = Cars(brand=form.brand.data, name=form.name.data, color=form.color.data, location=form.location.data)
        # Clear the form
        form.brand.data = ''
        form.name.data = ''
        form.color.data = ''
        form.location.data = ''
        
        # Add post data to database
        db.session.add(car)
        db.session.commit()
        
        flash("New Car Added")
    return render_template("create_car.html", form=form)

website/templates/admin.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content
    %}
    <h1 align="center">Admin Page</h1>
    {% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="home" href="/">Booking History</a>
            {% if current_user.id == 1 %}
          <a class="nav-item nav-link" id="admin" href="/admin">Admin</a>
          <a class="nav-item nav-link" id="create_car" href="/create_car">Edit Booking</a>
          
            {% endif%}
          <a class="nav-item nav-link" id="dashboard" href="/dashboard">Dashboard</a>
          <a class="nav-item nav-link" id="rental" href="/rental">Rental</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/create_car.html
{% extends "base.html" %} {% block title %}Create Entry{% endblock %} {% block content
    %}
    <h1 align="center">Add New Car</h1>

    <form action= "/create_car" method="POST">
        {{ form.hidden_tag() }}
        {{ form.brand.label(class="form-label")}}
        {{form.brand(
            class="form-control"
                  )}}
        </br>
        {{ form.name.label(class="form-label")}}
        {{form.name(
            class="form-control"
                 )}}
        </br>
        {{ form.color.label(class="form-label")}}
        {{form.color(
            class="form-control"
                  )}}
        </br>
        {{ form.location.label(class="form-label")}}
        {{form.location(
            class="form-control"
            
        )}}
        </br>
        {{form.submit(class="btn btn-secondary btn-submit") }}
    </form>



    {% endblock %} 

website/templates/dashboard.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content
    %}
    <h3>Dashboard</h3>

    <div class="card">
        <div class="card-header">
            Hello {{ current_user.user_name}}
        </div>
        <div class="card-body">
          <h5 class="card-title">Welcome to Your User Dashboard...</h5>
          <p class="card-text">
            <strong>Username:</strong>
            {{ current_user.user_name}}</br>

            <strong>FullName: </strong>
            {{ current_user.full_name}}</br>

            <strong>Email: </strong>
            {{ current_user.email}}</br>

            <strong>Age: </strong>
            {{ current_user.age}}</br>

            <strong>Date Joined: </strong>
            {{ current_user.date_created}}</br>
          </p>
          <a href="/logout" class="btn btn-secondary btn-sm">Logout</a>
        </div>

        <div class="card">
            <div class="card-header">
                Update Profile
            </div>
            <div class="card-body">
        
                <form action= "/dashboard" method="POST">
                    {{ form.hidden_tag() }}
                    {{ form.user_name.label(class="form-label")}}
                    {{form.user_name(
                        class="form-control",
                        value=name_to_update.user_name
                    )}}
                    </br>
                    {{ form.full_name.label(class="form-label")}}
                    {{form.full_name(
                        class="form-control",
                        value=name_to_update.full_name
                    )}}
                    </br>
                    {{ form.email.label(class="form-label")}}
                    {{form.email(
                        class="form-control",
                        value=name_to_update.email
                    )}}
                    </br>
                    {{ form.age.label(class="form-label")}}
                    {{form.age(
                        class="form-control",
                        value=name_to_update.age
                    )}}
                    </br>
                    {{form.submit(class="btn btn-secondary btn-submit") }}
                </form>
            
            </div>
          </div>

      </div>




{% endblock %}

website/templates/history.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} 
{% block content%}
    <h2 >Booking History</h2>
</br>

        <table class="table table-striped">
            <thead>
                <tr>
                  <th scope="col">Brand</th>
                  <th scope="col">Name</th>
                  <th scope="col">Color</th>
                  <th scope="col">City</th>
                </tr>
              </thead>
              <tbody>
                {% for rent in rental %}
                    <tr>
                    <th scope="row">{{ rented.brand }}</th>
                    <td>{{ rent.name }}</td>
                    <td>{{ rent.color }}</td>
                    <td>{{ rent.location }}</td>
                    <td>{{ rent.date_posted }}</td>
                    </tr>
                {% endfor%}
        </table>

        <a href="{{ url_for('views.rental')}}" class="btn btn-outline-secondary btn-sm">Back to Home</a>
    
{% endblock %} 

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.data }}
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/rental.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} 
{% block content%}
    <h1 align="center">Blog Posts...</h1>
</br>
    <div class="row">
        {% for car in rental %}
        <div class="col col-lg-5 shadow p-3 mb-5 bg-body rounded">
            <h3>{{ car.brand }}</h3></br>
            {{ car.name }}</br>
            {{ car.color }}</br>
            {{ car.location }}</br>
            {{ car.date_posted }}</br></br>

            <form action="/history" method="POST">
                <a href= "{{ url_for('views.history')}}"
            class=" btn btn-outline-secondary btn-sm">Book Now</a> 
            </form>
        </div>
        {% endfor %}
    </div>
    
{% endblock %} 

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="fullname">Full Name</label>
    <input
      type="text"
      class="form-control"
      id="fullname"
      name="fullname"
      placeholder="Enter full name"
    />
  </div>
  <div class="form-group">
    <label for="age">Age</label>
    <input
      type="number"
      class="form-control"
      id="age"
      name="age"
      placeholder="Enter your age"
    />
  </div>
  <div class="form-group">
    <label for="UserName">User Name</label>
    <input
      type="text"
      class="form-control"
      id="username"
      name="username"
      placeholder="Enter Username"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}